name: bayesian-mi
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - numpy
  - pandas
  - scikit-learn
  - tqdm
  - matplotlib
  - pylint=2.4.4
  - pip
  - pip:
    - seaborn
    - ipdb
    - conllu
    - adjusttext
    - statsmodels
